insert missing space
Otherwise, the error looks like:

> lochness.redcap.KeyringError: lochness > REDCAP > FAKE_AD,FAKE_HK,FAKE_LAnot found in keyring

cc @kcho